# Site settings
title: thiagodebastos
description:  'This is where Thiago de Bastos keeps you connected to things he creates, thinks and feels. An Art directed blog.'
url: localhost:4000 # the base hostname & protocol for your site

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: Thiago De Bastos
  email: thiago@xingur.com
  bio: Designer, thinker, creator.
  twitter: thiagodebastos
  github:  thiagodebastos


# general setting for Jekyll
# googleAnalytics: UA-XXXXX-X

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true

# Permalink structure and pagination options
relative_permalinks: true
permalink: pretty

# Set location for sass imports
sass:
  sass_dir: assets

# Disables the more accurate related posts for faster generating of the site
lsi: false

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']

# not supported by github pages
highlighter: pygments
